# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blogueando, que es gerundio
subtitle: Aventuras y desventuras de un mindundi en el planeta Tierra
email: islomar@gmail.com
url: https://islomar.es
description: >- # this means to ignore newlines until "baseurl:"
  Blog personal donde ¿escribo? sobre desarrollo de producto, psicología, antropología, budismo, Lean, eXtreme Programming (XP), DevOps o lo que me apetezca :-)
twitter_username: islomar
github_username: islomar
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Madrid
locale: "es-ES"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Isidro López"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Pastafari. Intento entender por qué hacemos lo que hacemos. <br> Escribo sobre desarrollo de producto, psicología, antropología, Lean, eXtreme Programming, DevOps, Kanban o lo que me apetezca :-)"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/islomar/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/islomar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/islomar"
    - label: "Goodreads"
      icon: "fas fa-fw fa-book"
      url: "https://www.goodreads.com/islomar"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:islomar@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/islomar/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/islomar"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/islomar"
    - label: "Goodreads"
      icon: "fas fa-fw fa-book"
      url: "https://www.goodreads.com/islomar"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true

comments:
  provider: "disqus"
  disqus:
    shortname: "https-islomar-es"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-171012598-1"
    anonymize_ip: true # default

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
